repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: pretty-format-json
      args: ['--autofix', "--indent=4", '--top-keys=meta']
    - id: requirements-txt-fixer
    - id: trailing-whitespace
      args:
        - "--markdown-linebreak-ext=md"
